// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIQOovRoT7WwzoPKUQvl1caKEw99Yflrs',
    appId: '1:1081479310118:web:cabe54de21894d5b132fe7',
    messagingSenderId: '1081479310118',
    projectId: 'holbegram-bd2e9',
    authDomain: 'holbegram-bd2e9.firebaseapp.com',
    storageBucket: 'holbegram-bd2e9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGa3RhP4toJRS_UDdts6p69gFaBd66KJM',
    appId: '1:1081479310118:android:f82e36843ee52066132fe7',
    messagingSenderId: '1081479310118',
    projectId: 'holbegram-bd2e9',
    storageBucket: 'holbegram-bd2e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlj9AUR09G3Qp0al1I86rviIOjzExYvkI',
    appId: '1:1081479310118:ios:321b85bc30767f9c132fe7',
    messagingSenderId: '1081479310118',
    projectId: 'holbegram-bd2e9',
    storageBucket: 'holbegram-bd2e9.firebasestorage.app',
    iosBundleId: 'com.example.holbegram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlj9AUR09G3Qp0al1I86rviIOjzExYvkI',
    appId: '1:1081479310118:ios:321b85bc30767f9c132fe7',
    messagingSenderId: '1081479310118',
    projectId: 'holbegram-bd2e9',
    storageBucket: 'holbegram-bd2e9.firebasestorage.app',
    iosBundleId: 'com.example.holbegram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIQOovRoT7WwzoPKUQvl1caKEw99Yflrs',
    appId: '1:1081479310118:web:003ee11a7e042240132fe7',
    messagingSenderId: '1081479310118',
    projectId: 'holbegram-bd2e9',
    authDomain: 'holbegram-bd2e9.firebaseapp.com',
    storageBucket: 'holbegram-bd2e9.firebasestorage.app',
  );
}
